### ISSUE TITLE
Compatibility with older versions of Python?

### ISSUE THREAD

**Issue by tmuguet** [ssfdust/flask-sqlalchemy-stubs#1]
Hi,

Thanks for your work! Unfortunately, as I'm using Python 3.6, I'm unable to test it. Is there a reason why only Python 3.8+ is supported? Would it be possible to have it also for Python 3.6?

Thanks,
Thomas

**Comment by ssfdust** [comment]
Yes, it's possible. My default python version is 3.8, so poetry freeze the version of python.
I also import annotations module which is incompatible with 3.6,  but I am going to catch up with the latest flask-sqlalchemy package this weekend, which needs to rebuild the stubs only.
If you could wait for some days with patience, it will be there.

**Comment by tmuguet** [comment]
Hi @ssfdust ,
Many thanks for the quick update!! It seems to work well! Now I have to fix all the bugs it (correctly!) found 😅
