### ISSUE TITLE
mypy.ini:2: error: Error importing plugin 'flasksqlamypy': No module named 'flasksqlamypy'

### ISSUE THREAD

**Issue by StevenDas-Tomo** [ssfdust/flask-sqlalchemy-stubs#7]
I added the `flasksqlamypy` plugin to my `mypy.ini` as suggested by the docs, but ended up hitting the following error when running `mypy`:

```
mypy.ini:2: error: Error importing plugin 'flasksqlamypy': No module named 'flasksqlamypy'
```

Looking in my `site-packages` folder, it doesn't appear that `flasksqlamypy` is getting installed as a top-level module when installing from PyPi.

Does something need to be fixed with the package configuration?

**Comment by ssfdust** [comment]
Hello,
this package has not been uploaded to pypi. You probably installed another package.Please try:
```pip install git+https://github.com/ssfdust/flask-sqlalchemy-stubs.git --upgrade```

**Comment by StevenDas-Tomo** [comment]
I see: thanks for the fast reply, @ssfdust.

Any plans to put this on PyPi? Seems like it could be really useful.

**Comment by ssfdust** [comment]
I would like to combine the origin flask-sqlalchemy and this stubs. Because it's not that easy to manage package and its stubs from different versions.

After https://github.com/bryanforbes/gino-stubs/issues/19 is resolved, I will create pr for flask-sqlalchemy.

**Comment by StevenDas-Tomo** [comment]
Awesome, sounds great @ssfdust!

**Comment by ssfdust** [comment]
Closed.
